version: '3.9'

services:
  db:
    image: postgres:16.8
    container_name: digital_wallet_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app_db
    volumes:
      - digital_wallet_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital_wallet_app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CORS_ORIGINS: ${CORS_ORIGINS}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      PROVIDER_AGENCY: ${PROVIDER_AGENCY}
      PROVIDER_BANK: ${PROVIDER_BANK}
      PROVIDER_NAME: ${PROVIDER_NAME}
    depends_on:
      - db
    networks:
      - app-network

volumes:
  digital_wallet_data:

networks:
  app-network:
    driver: bridge
