server:
  servlet:
    context-path: /

spring:
  application:
    name: digital-wallet-api
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/db-master.xml
    drop-first: false
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true

api:
  provider:
    agency: ${PROVIDER_AGENCY}
    bank: ${PROVIDER_BANK}
    name: ${PROVIDER_NAME}
  security:
    jwt-secret-key: ${JWT_SECRET_KEY}
  swagger:
    security-scheme-name: bearerAuth